import concurrent.futures
import threading
from reconx.core.engine import Module
from reconx.utils.http import check_username_url
from reconx.utils.output import print_found, print_not_found, print_error, print_info


SITES = [
    {
        "name": "GitHub",
        "url": "https://github.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Twitter / X",
        "url": "https://twitter.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Instagram",
        "url": "https://www.instagram.com/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Reddit",
        "url": "https://www.reddit.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "TikTok",
        "url": "https://www.tiktok.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "YouTube",
        "url": "https://www.youtube.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "LinkedIn",
        "url": "https://www.linkedin.com/in/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Facebook",
        "url": "https://www.facebook.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Pinterest",
        "url": "https://www.pinterest.com/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Twitch",
        "url": "https://www.twitch.tv/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Snapchat",
        "url": "https://www.snapchat.com/add/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Medium",
        "url": "https://medium.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Dev.to",
        "url": "https://dev.to/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "GitLab",
        "url": "https://gitlab.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bitbucket",
        "url": "https://bitbucket.org/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Docker Hub",
        "url": "https://hub.docker.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "npm",
        "url": "https://www.npmjs.com/~{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PyPI",
        "url": "https://pypi.org/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Steam",
        "url": "https://steamcommunity.com/id/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Spotify",
        "url": "https://open.spotify.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "SoundCloud",
        "url": "https://soundcloud.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Flickr",
        "url": "https://www.flickr.com/people/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Vimeo",
        "url": "https://vimeo.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "About.me",
        "url": "https://about.me/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Gravatar",
        "url": "https://gravatar.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Keybase",
        "url": "https://keybase.io/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hacker News",
        "url": "https://news.ycombinator.com/user?id={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Stack Overflow",
        "url": "https://stackoverflow.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "HackerOne",
        "url": "https://hackerone.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bugcrowd",
        "url": "https://bugcrowd.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Lichess",
        "url": "https://lichess.org/@/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Chess.com",
        "url": "https://www.chess.com/member/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Patreon",
        "url": "https://www.patreon.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "BuyMeACoffee",
        "url": "https://www.buymeacoffee.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Ko-fi",
        "url": "https://ko-fi.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Substack",
        "url": "https://{username}.substack.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "WordPress",
        "url": "https://{username}.wordpress.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Tumblr",
        "url": "https://{username}.tumblr.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Blogger",
        "url": "https://{username}.blogspot.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "DeviantArt",
        "url": "https://www.deviantart.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Foursquare",
        "url": "https://foursquare.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Letterboxd",
        "url": "https://letterboxd.com/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Goodreads",
        "url": "https://www.goodreads.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Last.fm",
        "url": "https://www.last.fm/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Trello",
        "url": "https://trello.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "SlideShare",
        "url": "https://www.slideshare.net/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Pastebin",
        "url": "https://pastebin.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Replit",
        "url": "https://replit.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "CodePen",
        "url": "https://codepen.io/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "JSFiddle",
        "url": "https://jsfiddle.net/user/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mastodon",
        "url": "https://mastodon.social/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Discord",
        "url": "https://discord.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Telegram",
        "url": "https://t.me/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "X (Twitter) API",
        "url": "https://nitter.net/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Quora",
        "url": "https://www.quora.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Archive.org",
        "url": "https://archive.org/details/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Cracked.to",
        "url": "https://cracked.to/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "0x00sec",
        "url": "https://0x00sec.org/u/{username}/summary",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hack The Box",
        "url": "https://app.hackthebox.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "TryHackMe",
        "url": "https://tryhackme.com/p/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "OpenSea",
        "url": "https://opensea.io/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Etsy",
        "url": "https://www.etsy.com/shop/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Untappd",
        "url": "https://untappd.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "TripAdvisor",
        "url": "https://www.tripadvisor.com/Profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Yelp",
        "url": "https://www.yelp.com/user_details?userid={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Amazon",
        "url": "https://www.amazon.com/gp/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "eBay",
        "url": "https://www.ebay.com/usr/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wikipedia",
        "url": "https://en.wikipedia.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wikidata",
        "url": "https://www.wikidata.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Imgur",
        "url": "https://imgur.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "VirusTotal",
        "url": "https://www.virustotal.com/ui/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Shodan",
        "url": "https://www.shodan.io/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Censys",
        "url": "https://search.censys.io/profiles/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Have I Been Pwned",
        "url": "https://haveibeenpwned.com",
        "check_type": "custom",
    },
    {
        "name": "GitHub Gist",
        "url": "https://gist.github.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Packer",
        "url": "https://packer.io/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "SourceForge",
        "url": "https://sourceforge.net/u/{username}/profile",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Kaggle",
        "url": "https://www.kaggle.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Adobe Portfolio",
        "url": "https://{username}.myportfolio.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Behance",
        "url": "https://www.behance.net/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Dribbble",
        "url": "https://dribbble.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Figma",
        "url": "https://www.figma.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Clubhouse",
        "url": "https://www.clubhouse.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Periscope",
        "url": "https://www.pscp.tv/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mixcloud",
        "url": "https://www.mixcloud.com/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bandcamp",
        "url": "https://{username}.bandcamp.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Kick",
        "url": "https://kick.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Rumble",
        "url": "https://rumble.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Threads",
        "url": "https://www.threads.net/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bluesky",
        "url": "https://bsky.app/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mastodon (mastodon.social)",
        "url": "https://mastodon.social/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PerfCast",
        "url": "https://perfcast.cc/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Rajce",
        "url": "https://{username}.rajce.idnes.cz/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Launchpad",
        "url": "https://launchpad.net/~{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "OSF",
        "url": "https://osf.io/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Cloudflare",
        "url": "https://www.cloudflare.com",
        "check_type": "custom",
    },
    {
        "name": "Product Hunt",
        "url": "https://www.producthunt.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Crew",
        "url": "https://www.crew.co/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Angellist",
        "url": "https://wellfound.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Investing.com",
        "url": "https://www.investing.com/traders/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Cash.app",
        "url": "https://cash.app/${username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Venmo",
        "url": "https://venmo.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Gumroad",
        "url": "https://{username}.gumroad.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Loom",
        "url": "https://www.loom.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Notion",
        "url": "https://www.notion.so/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Carrd",
        "url": "https://{username}.carrd.co",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Linktree",
        "url": "https://linktr.ee/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Beacons",
        "url": "https://beacons.ai/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Muck Rack",
        "url": "https://muckrack.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Musescore",
        "url": "https://musescore.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Genius",
        "url": "https://genius.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Animoto",
        "url": "https://animoto.com/play/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Channel Meter",
        "url": "https://channelmeter.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Jekyll",
        "url": "https://{username}.github.io",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Ringory",
        "url": "https://ringory.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Cent.co",
        "url": "https://cent.co/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "F6S",
        "url": "https://www.f6s.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Freelancer",
        "url": "https://www.freelancer.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Upwork",
        "url": "https://www.upwork.com/freelancers/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Fiverr",
        "url": "https://www.fiverr.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PeoplePerHour",
        "url": "https://www.peopleperhour.com/freelancer/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Guru",
        "url": "https://www.guru.com/d/freelancers/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "9GAG",
        "url": "https://9gag.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "iNaturalist",
        "url": "https://www.inaturalist.org/people/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Roblox",
        "url": "https://www.roblox.com/users/profile?username={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Spotify (artist)",
        "url": "https://open.spotify.com/artist/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mixi",
        "url": "https://mixi.jp/show_profile.pl?id={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Amino",
        "url": "https://aminoapps.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Badoo",
        "url": "https://badoo.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bumble",
        "url": "https://bumble.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Zillow",
        "url": "https://www.zillow.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Zomato",
        "url": "https://www.zomato.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Strava",
        "url": "https://www.strava.com/athletes/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "MapMyRun",
        "url": "https://www.mapmyrun.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Crunchyroll",
        "url": "https://www.crunchyroll.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Funimation",
        "url": "https://www.funimation.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "LiveJournal",
        "url": "https://{username}.livejournal.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Ask.fm",
        "url": "https://ask.fm/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Weibo",
        "url": "https://weibo.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Plurk",
        "url": "https://www.plurk.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Skyrock",
        "url": "https://{username}.skyrock.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "NPMJS",
        "url": "https://www.npmjs.com/~{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Packagist",
        "url": "https://packagist.org/users/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "RubyGems",
        "url": "https://rubygems.org/profiles/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Crates.io",
        "url": "https://crates.io/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PyPI",
        "url": "https://pypi.org/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Forum & Community Sites
    # ============================================
    {
        "name": "Something Awful",
        "url": "https://forums.somethingawful.com/member.php?action=getinfo&username={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "XDA Developers",
        "url": "https://forum.xda-developers.com/m/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Steam Community",
        "url": "https://steamcommunity.com/discussions/forum/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "BodyBuilding.com",
        "url": "https://forum.bodybuilding.com/member.php?u={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Shoryuken",
        "url": "https://shoryuken.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Coding & Developer Platforms
    # ============================================
    {
        "name": "Codeberg",
        "url": "https://codeberg.org/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "SourceHut",
        "url": "https://sr.ht/~{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Gitee",
        "url": "https://gitee.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hashnode",
        "url": "https://hashnode.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "DevBlog",
        "url": "https://dev.to/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Polywork",
        "url": "https://polywork.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "StackBlitz",
        "url": "https://stackblitz.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Codesandbox",
        "url": "https://codesandbox.io/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "JSFiddle Profile",
        "url": "https://jsfiddle.net/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Observable",
        "url": "https://observablehq.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "ShaderToy",
        "url": "https://www.shadertoy.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Replit Profile",
        "url": "https://replit.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Arduino Forum",
        "url": "https://forum.arduino.cc/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Raspberry Pi Forum",
        "url": "https://forums.raspberrypi.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Social Media (Additional)
    # ============================================
    {
        "name": "Truth Social",
        "url": "https://truthsocial.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Parler",
        "url": "https://parler.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Gab",
        "url": "https://gab.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mastodon (mastodon.online)",
        "url": "https://mastodon.online/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mastodon (fosstodon)",
        "url": "https://fosstodon.org/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Post.news",
        "url": "https://post.news/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Cohost",
        "url": "https://cohost.org/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Reddit (cakeday)",
        "url": "https://www.reddit.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Quora",
        "url": "https://www.quora.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Gaming Platforms
    # ============================================
    {
        "name": "Xbox Gamertag",
        "url": "https://xboxgamertag.com/search/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PSN Profiles",
        "url": "https://psnprofiles.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Steam Group",
        "url": "https://steamcommunity.com/groups/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "OP.GG (LoL)",
        "url": "https://www.op.gg/summoners/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "U.gg",
        "url": "https://u.gg/lol/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Faceit",
        "url": "https://www.faceit.com/en/players/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Epic Games",
        "url": "https://fortnitetracker.com/profile/all/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mojang/Minecraft",
        "url": "https://namemc.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Skribbl.io",
        "url": "https://skribbl.io/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Chess.com (2019)",
        "url": "https://www.chess.com/member/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Aim Lab",
        "url": "https://aimlab.gg/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Tetrio",
        "url": "https://ch.tetr.io/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Osu!",
        "url": "https://osu.ppy.sh/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Speedrun.com",
        "url": "https://www.speedrun.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "BoardGameGeek",
        "url": "https://boardgamegeek.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Music & Audio
    # ============================================
    {
        "name": "Rate Your Music",
        "url": "https://rateyourmusic.com/~{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Discogs",
        "url": "https://www.discogs.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "SoundClick",
        "url": "https://www.soundclick.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Audiomack",
        "url": "https://audiomack.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bandcamp (daily)",
        "url": "https://daily.bandcamp.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Lollapalooza",
        "url": "https://www.lollapalooza.com/artists/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Video & Streaming
    # ============================================
    {
        "name": "Dailymotion",
        "url": "https://www.dailymotion.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Vimeo",
        "url": "https://vimeo.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Twitch ( Clips)",
        "url": "https://clips.twitch.tv/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "YouTube Channel",
        "url": "https://www.youtube.com/c/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "YouTube (legacy)",
        "url": "https://www.youtube.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "DTube",
        "url": "https://d.tube/c/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PeerTube",
        "url": "https://framatube.org/c/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Picarto",
        "url": "https://picarto.tv/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Trovo",
        "url": "https://trovo.live/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Art & Design
    # ============================================
    {
        "name": "ArtStation",
        "url": "https://www.artstation.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Behance Portfolio",
        "url": "https://www.behance.net/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Dribbble (alt)",
        "url": "https://dribbble.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Figma Community",
        "url": "https://www.figma.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Canva",
        "url": "https://www.canva.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Unsplash",
        "url": "https://unsplash.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "500px",
        "url": "https://500px.com/p/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Getty Images",
        "url": "https://www.gettyimages.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Scribble",
        "url": "https://scribble.nu/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Drawception",
        "url": "https://drawception.com/player/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Sketchfab",
        "url": "https://sketchfab.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Poly",
        "url": "https://poly.google.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Pinterest (boards)",
        "url": "https://www.pinterest.com/{username}/boards/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Vsco",
        "url": "https://vsco.co/{username}/gallery",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Ello",
        "url": "https://ello.co/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Glass",
        "url": "https://glass.photo/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Creepy",
        "url": "https://www.creepy.dev/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Colors",
        "url": "https://colors.live/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Pixiv",
        "url": "https://www.pixiv.net/en/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "DeviantArt (journal)",
        "url": "https://www.deviantart.com/{username}/journal",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Finance & Shopping
    # ============================================
    {
        "name": "PayPal",
        "url": "https://www.paypal.com/paypalme/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wise",
        "url": "https://wise.com/pay/me/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Monzo",
        "url": "https://monzo.com/pay/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Revolut",
        "url": "https://revolut.com/pay/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Kofi (extra)",
        "url": "https://ko-fi.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "LiberaPay",
        "url": "https://liberapay.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Patreon",
        "url": "https://www.patreon.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Subscribestar",
        "url": "https://www.subscribestar.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "OnlyFans",
        "url": "https://onlyfans.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Fansly",
        "url": "https://fansly.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Mercari",
        "url": "https://www.mercari.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Poshmark",
        "url": "https://poshmark.com/closet/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Depop",
        "url": "https://www.depop.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "StockX",
        "url": "https://stockx.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Blogging & Publishing
    # ============================================
    {
        "name": "Ghost",
        "url": "https://{username}.ghost.io",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Medium (custom)",
        "url": "https://medium.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hashnode Blog",
        "url": "https://{username}.hashnode.dev",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Blogger",
        "url": "https://{username}.blogspot.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Write.as",
        "url": "https://write.as/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Svbtle",
        "url": "https://{username}.svbtle.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Telegraph",
        "url": "https://telegra.ph/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Notion Blog",
        "url": "https://{username}.notion.site",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bear Blog",
        "url": "https://{username}.bearblog.dev",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bluesky",
        "url": "https://bsky.app/profile/{username}.bsky.social",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Substack (publius)",
        "url": "https://publius.substack.com",
        "check_type": "custom",
    },
    # ============================================
    # Link-in-Bio & Profile Pages
    # ============================================
    {
        "name": "Lnk.Bio",
        "url": "https://lnk.bio/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bento.me",
        "url": "https://bento.me/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Solo.to",
        "url": "https://solo.to/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Milkshake",
        "url": "https://milkshake.app/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "HeyLink",
        "url": "https://heylink.me/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Willow",
        "url": "https://willow.gg/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "MyURL",
        "url": "https://myurl.bio/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Many.link",
        "url": "https://many.link/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Taplink",
        "url": "https://taplink.cc/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Direct.me",
        "url": "https://direct.me/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Stan Store",
        "url": "https://stan.store/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Pushbio",
        "url": "https://pushbio.co/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Dating & Social
    # ============================================
    {
        "name": "OkCupid",
        "url": "https://www.okcupid.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Tinder (public)",
        "url": "https://www.tinder.com/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hinge",
        "url": "https://hinge.co/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "MeetMe",
        "url": "https://www.meetme.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Tagged",
        "url": "https://www.tagged.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hi5",
        "url": "https://www.hi5.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Badoo (profile)",
        "url": "https://badoo.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Plenty of Fish",
        "url": "https://www.pof.com/viewprofile.aspx?profile_id={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Zoosk",
        "url": "https://www.zoosk.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Grindr",
        "url": "https://www.grindr.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Fitness & Health
    # ============================================
    {
        "name": "Fitbit",
        "url": "https://www.fitbit.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Strava",
        "url": "https://www.strava.com/athletes/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "MyFitnessPal",
        "url": "https://www.myfitnesspal.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Nike Run Club",
        "url": "https://www.nike.com/nike-club/member/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Garmin Connect",
        "url": "https://connect.garmin.com/modern/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Runtastic",
        "url": "https://www.runtastic.com/en/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Food & Travel
    # ============================================
    {
        "name": "Untappd (check-in)",
        "url": "https://untappd.com/user/{username}/checkins",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "AllTrails",
        "url": "https://www.alltrails.com/members/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Trip.com",
        "url": "https://www.trip.com/members/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Booking.com",
        "url": "https://www.booking.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Airbnb",
        "url": "https://www.airbnb.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Yelp (profile)",
        "url": "https://www.yelp.com/user_details?userid={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Education & Research
    # ============================================
    {
        "name": "ResearchGate",
        "url": "https://www.researchgate.net/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Academia.edu",
        "url": "https://independent.academia.edu/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Google Scholar",
        "url": "https://scholar.google.com/citations?user={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "ORCID",
        "url": "https://orcid.org/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Coursera",
        "url": "https://www.coursera.org/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Udemy",
        "url": "https://www.udemy.com/user/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Khan Academy",
        "url": "https://www.khanacademy.org/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Duolingo",
        "url": "https://www.duolingo.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "EdX",
        "url": "https://courses.edx.org/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Udacity",
        "url": "https://www.udacity.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Codecademy",
        "url": "https://www.codecademy.com/profiles/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "freeCodeCamp",
        "url": "https://www.freecodecamp.org/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "LeetCode",
        "url": "https://leetcode.com/{username}/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "HackerRank",
        "url": "https://www.hackerrank.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Codeforces",
        "url": "https://codeforces.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Codewars",
        "url": "https://www.codewars.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Topcoder",
        "url": "https://www.topcoder.com/members/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Exercism",
        "url": "https://exercism.org/profiles/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Kaggle (2019)",
        "url": "https://www.kaggle.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Brilliant",
        "url": "https://brilliant.org/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "TED",
        "url": "https://www.ted.com/profiles/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Cybersecurity & Infosec
    # ============================================
    {
        "name": "PentestIT",
        "url": "https://pentestit.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "VirusTotal Forum",
        "url": "https://forum.virustotal.com/u/{username}/summary",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "CyberChef",
        "url": "https://gchq.github.io/CyberChef",
        "check_type": "custom",
    },
    {
        "name": "Exploit Database",
        "url": "https://www.exploit-db.com/search?q={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "CVE Details",
        "url": "https://www.cvedetails.com/google-search-results.php?q={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "GreyNoise",
        "url": "https://www.greynoise.io/viz/ip/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Binary Ninja",
        "url": "https://cloud.binary.ninja/api/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "CrowdStrike",
        "url": "https://falcon.crowdstrike.com/community/search/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "SANS Profile",
        "url": "https://www.sans.org/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Wiki & Knowledge
    # ============================================
    {
        "name": "Fandom Wiki",
        "url": "https://www.fandom.com/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wikimedia",
        "url": "https://meta.wikimedia.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wikidata",
        "url": "https://www.wikidata.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wiktionary",
        "url": "https://en.wiktionary.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wikinews",
        "url": "https://en.wikinews.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "WikiBooks",
        "url": "https://en.wikibooks.org/wiki/User:{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Asian Social Networks
    # ============================================
    {
        "name": "Douyin",
        "url": "https://www.douyin.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Bilibili",
        "url": "https://space.bilibili.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Zhihu",
        "url": "https://www.zhihu.com/people/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "WeChat (public)",
        "url": "https://weixin.sogou.com/weixin?type=1&query={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "VK",
        "url": "https://vk.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "OK.ru",
        "url": "https://ok.ru/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "LINE",
        "url": "https://line.me/ti/p/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "KakaoTalk",
        "url": "https://kakao.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Naver",
        "url": "https://blog.naver.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Regional Platforms
    # ============================================
    {
        "name": "Mixi (JP)",
        "url": "https://mixi.jp/show_profile.pl?id={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Ameblo (JP)",
        "url": "https://ameblo.jp/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Renren (CN)",
        "url": "http://www.renren.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Tieba (CN)",
        "url": "https://tieba.baidu.com/home/main?un={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Sina Blog (CN)",
        "url": "https://blog.sina.com.cn/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Xing (DE)",
        "url": "https://www.xing.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "StayFriends (DE)",
        "url": "https://www.stayfriends.de/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "VKontakte (RU)",
        "url": "https://vk.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Odnoklassniki (RU)",
        "url": "https://ok.ru/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Taringa (LATAM)",
        "url": "https://www.taringa.net/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    # ============================================
    # Miscellaneous & Productivity
    # ============================================
    {
        "name": "Notion (site)",
        "url": "https://{username}.notion.site",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Coda",
        "url": "https://coda.io/@{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Airtable",
        "url": "https://airtable.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Notion.so",
        "url": "https://www.notion.so/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Miro",
        "url": "https://miro.com/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "FigJam",
        "url": "https://www.figma.com/jam/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Trello (board)",
        "url": "https://trello.com/b/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Asana",
        "url": "https://app.asana.com/0/{username}/list",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Monday.com",
        "url": "https://{username}.monday.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Basecamp",
        "url": "https://{username}.basecamphq.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Wrike",
        "url": "https://www.wrike.com/workspace/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Toggl",
        "url": "https://track.toggl.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Slack (community)",
        "url": "https://{username}.slack.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Discord (server)",
        "url": "https://discord.gg/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "RSS Feed",
        "url": "https://{username}.rss.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Podcast (Anchor)",
        "url": "https://anchor.fm/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Spotify (playlist)",
        "url": "https://open.spotify.com/playlist/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Apple Podcasts",
        "url": "https://podcasts.apple.com/podcast/id{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Goodreads (list)",
        "url": "https://www.goodreads.com/review/list/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Letterboxd (list)",
        "url": "https://letterboxd.com/{username}/list/",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "IMDb",
        "url": "https://www.imdb.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "TMDB",
        "url": "https://www.themoviedb.org/u/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "AniList",
        "url": "https://anilist.co/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "MyAnimeList",
        "url": "https://myanimelist.net/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Kitsu",
        "url": "https://kitsu.io/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Simkl",
        "url": "https://simkl.com/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Yelp (reviews)",
        "url": "https://www.yelp.com/user_details_reviews?userid={username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Zillow (saved)",
        "url": "https://www.zillow.com/profile/{username}/saved-homes",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Home Depot Community",
        "url": "https://community.homedepot.com/people/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "iFixit",
        "url": "https://www.ifixit.com/User/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Instructables",
        "url": "https://www.instructables.com/member/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Thingiverse",
        "url": "https://www.thingiverse.com/{username}/designs",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hackster.io",
        "url": "https://www.hackster.io/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Arduino Project Hub",
        "url": "https://create.arduino.cc/projecthub/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Hackaday",
        "url": "https://hackaday.io/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "IFTTT",
        "url": "https://ifttt.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Zapier",
        "url": "https://zapier.com/developer/public/app/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "n8n",
        "url": "https://n8n.cloud/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Make.com",
        "url": "https://www.make.com/en/profile/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Postman",
        "url": "https://www.postman.com/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "RapidAPI",
        "url": "https://rapidapi.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Swagger/SmartBear",
        "url": "https://smartbear.com/user/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Stoplight",
        "url": "https://stoplight.io/studio/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "GraphQL Hub",
        "url": "https://graphql.org/users/{username}",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Ngrok",
        "url": "https://{username}.ngrok.io",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Render",
        "url": "https://{username}.onrender.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Netlify (site)",
        "url": "https://{username}.netlify.app",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Vercel (site)",
        "url": "https://{username}.vercel.app",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Railway",
        "url": "https://{username}.up.railway.app",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Fly.io",
        "url": "https://{username}.fly.dev",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "GitHub Pages",
        "url": "https://{username}.github.io",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "GitLab Pages",
        "url": "https://{username}.gitlab.io",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Cloudflare Pages",
        "url": "https://{username}.pages.dev",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Surge.sh",
        "url": "https://{username}.surge.sh",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "InfinityFree",
        "url": "https://{username}..rf.gd",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Glitch",
        "url": "https://{username}.glitch.me",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "PythonAnywhere",
        "url": "https://{username}.pythonanywhere.com",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
    {
        "name": "Replit (site)",
        "url": "https://{username}.replit.app",
        "check_type": "status_code",
        "match": [200],
        "exclude": [404],
    },
]


lock = threading.Lock()


def _check_site(site, username, timeout):
    """Check a single site for the username."""
    if site["check_type"] == "custom":
        return {"site": site["name"], "status": "skipped", "url": site["url"]}

    url = site["url"].format(username=username)
    try:
        resp = check_username_url(url, username, timeout=timeout)
        if resp is None:
            return {"site": site["name"], "status": "error", "url": url}

        status_code = resp.status_code
        if status_code in site["match"]:
            return {"site": site["name"], "status": "found", "url": url}
        elif status_code in site.get("exclude", [404]):
            return {"site": site["name"], "status": "not_found", "url": url}
        else:
            return {"site": site["name"], "status": "unknown", "url": url, "code": status_code}
    except Exception:
        return {"site": site["name"], "status": "error", "url": url}


class UsernameRecon(Module):
    """Search for a username across 100+ platforms."""

    name = "username"
    description = "Search username across 100+ social media platforms and websites"

    def run(self, target, workers=20):
        """Run username reconnaissance across all platforms."""
        print_info(f"Searching for username: {target}")
        print_info(f"Checking {len(SITES)} platforms with {workers} threads...")

        found_count = 0
        not_found_count = 0
        error_count = 0

        with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(_check_site, site, target, self.timeout): site
                for site in SITES
            }
            for future in concurrent.futures.as_completed(futures):
                result = future.result()
                if result["status"] == "found":
                    print_found(f"{result['site']}: {result['url']}")
                    self.add_result(result["site"], result["url"], "found")
                    found_count += 1
                elif result["status"] == "not_found":
                    print_not_found(f"{result['site']}: not found")
                    not_found_count += 1
                elif result["status"] == "skipped":
                    pass
                else:
                    error_count += 1

        from reconx.utils.output import print_summary
        print_summary(found_count, not_found_count, error_count)

        return self.results
