[package]
name = "reconx-common"
version.workspace = true
edition.workspace = true

[dependencies]
reconx-core = { path = "../reconx-core" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
